### ISSUE TITLE
Fix code repetition in tests

### ISSUE THREAD

**Issue by k4m4** [unmock/freddo#4]
- Use `ava`'s [`test.beforeAll`](https://github.com/avajs/ava/blob/master/docs/01-writing-tests.md#before--after-hooks) to run `clearFreddoCache()` before each test (in favor of DRY).

**Comment by carolstran** [comment]
👋 @k4m4, I tried tackling this one (in the [less-repetitive-tests](https://github.com/unmock/freddo/tree/less-repetitive-tests) branch) but ran into a slight issue.

Four of the tests continue to fail: 

```
status code
headers
pass function as expected value
redirectsTo
```

I verified that the `beforeEach` is running every test and I've been reading the documentation/other forums. Maybe it has something to do with the tests running concurrently? Or it also could be something obvious that my jetlagged brain is missing 🤪

Any insights appreciated - thanks!

PS. I'd also be curious about why you decided to use AVA for testing? It's nice, I had just never seen it before!

**Comment by k4m4** [comment]
Hi @carolstran! As you correctly predicted, it seems that the tests need to be run [serially](https://github.com/avajs/ava/blob/master/docs/01-writing-tests.md#running-tests-serially) so that the cache is cleared at the beginning of each individual test. As for why I use `AVA`, I guess I have been using it since I first started experimenting with Node.js (and have stuck with it ever since). Also, I greatly admire all of @sindresorhus's work.

**Comment by carolstran** [comment]
Ah totally missed that page in the docs, thank you @k4m4 🙌  I'll finish this up tomorrow! And thanks for talking about why you use AVA - very interesting, I might have to explore more of @sindresorhus's work too 😍 💯

**Comment by k4m4** [comment]
Of course, no problem! All tests seem to be passing now, so I believe we are ready to merge `less-repetitive-tests`! 😀

**Comment by carolstran** [comment]
Oh nice, just saw your commit. Thanks! I'll open a PR now and then you can merge it later today assuming everything's fine (I always feel weird merging my own PRs 😆 )
